FROM jenkins/jenkins:lts

USER root

# Instala Docker CLI para que Jenkins pueda usar docker build
RUN apt-get update && \
    apt-get install -y docker.io && \
    apt-get clean

# Opcional: instala docker-compose si también lo usas
RUN curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" \
    -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose

USER jenkins
